name: MLflow Advance Workflow

on:
  push:
    branches: [ main ]

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.12'

      - name: Install dependencies
        run: |
          pip install mlflow dagshub pandas scikit-learn docker virtualenv

      - name: Run mlflow project
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          export MLFLOW_TRACKING_URI=https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/my-first-repo.mlflow
          mlflow run MLProject/ --env-manager local
          mlflow artifacts download -u "runs:/$(mlflow last-run --experiment-name 'HousePriceProject' -q)/model" --dst-path "local_model"

      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          MODEL_PATH=$(find . -type d -name "model" | grep "artifacts/model" | head -n 1)
          echo "MODEL_PATH=$MODEL_PATH" >> $GITHUB_OUTPUT

      - name: Install Python dependencies
        run: echo "Virtualenv ready for Docker build."

      - name: Upload to Google Drive
        run: echo "Artifacts saved for Docker construction."

      - name: Build Docker Model
        run: |
          mlflow models build-docker -m "local_model/model" -n ackerman19/house_price_prediction:latest --env-manager virtualenv
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker Image
        run: echo "Image ready."

      - name: Push Docker Image
        run: |
          docker push ackerman19/house_price_prediction:latest

      - name: Complete job
        run: echo "Advance Workflow Sukses!"
