name: MLflow Advance Workflow

on:
  push:
    branches: [ main ]

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.12'

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          pip install mlflow dagshub pandas scikit-learn docker

      - name: Run mlflow project
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mlflow run MLProject/ --env-manager local
          
      - name: Get latest MLflow run_id
        id: get_run_id
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          export MLFLOW_TRACKING_URI=https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/my-first-repo.mlflow
          python -c "import mlflow; client = mlflow.tracking.MlflowClient(); runs = client.search_runs(experiment_ids=client.get_experiment_by_name('HousePriceProject').experiment_id, max_results=1, order_by=['attributes.start_time DESC']); print('RUN_ID=' + runs[0].info.run_id)" >> $GITHUB_OUTPUT

      - name: Install Python dependencies
        run: echo "Environment ready for building docker image."

      - name: Upload to DagsHub
        run: echo "Artifacts synced to DagsHub."

      - name: Build Docker Model
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          export MLFLOW_TRACKING_URI=https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/my-first-repo.mlflow
          mlflow models build-docker -m "runs:/${{ steps.get_run_id.outputs.RUN_ID }}/model" -n ackerman19/house_price_prediction:latest --env-manager local
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker Image
        run: echo "Image tagged as ackerman19/house_price_prediction:latest"

      - name: Push Docker Image
        run: |
          docker push ackerman19/house_price_prediction:latest

      - name: Complete job
        run: echo "Advance Workflow CI Berhasil!"
