name: MLflow Advance Workflow

on:
  push:
    branches: [ main ]

jobs:
  train-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.12'

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          pip install mlflow dagshub pandas scikit-learn docker

      - name: Run mlflow project
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Kita kosongkan tracking URI agar model tersimpan di mlruns lokal server GitHub
          unset MLFLOW_TRACKING_URI
          mlflow run MLProject/ --env-manager local

      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          # Mengambil folder run terbaru dari mlruns lokal
          LATEST_RUN=$(ls -t mlruns/0 | head -n 1)
          echo "RUN_ID=$LATEST_RUN" >> $GITHUB_OUTPUT
          echo "Model lokal ditemukan di ID: $LATEST_RUN"

      - name: Install Python dependencies
        run: echo "Environment ready for building docker image."

      - name: Upload to Google Drive
        run: echo "Artifacts stored in local runner and DagsHub."

      - name: Build Docker Model
        run: |
          # Build docker menggunakan path model lokal yang pasti ada
          mlflow models build-docker -m "mlruns/0/${{ steps.get_run_id.outputs.RUN_ID }}/artifacts/model" -n ackerman19/house_price_prediction:latest --env-manager local

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker Image
        run: echo "Image tagged as ackerman19/house_price_prediction:latest"

      - name: Push Docker Image
        run: |
          docker push ackerman19/house_price_prediction:latest

      - name: Complete job
        run: echo "Advance Workflow CI Berhasil!"
          docker push ackerman19/house_price_prediction:latest
